name: platinum_list
description: A sdk client for work with Platinum list service.
version: 1.0.0
repository: https://github.com/romancores/platinum_list

environment:
  sdk: ^3.0.5

dependencies:
  comparer: ^2.0.1
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  test: ^1.21.3
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.0